### ISSUE TITLE
Multiple instance issue

### ISSUE THREAD

**Issue by kanongil** [hapijs/marker#1]
It's very possible to have multiple instances of a module inside a codebase, which will break the intention behind this module.

To be safe, you need to store the Map in a global somewhere. I would probably do something like:

```js
let map = global[Symbol.for('@hapi/marker')];
if (!map) {
    map = new Map();
    Object.defineProperty(global, Symbol.for('@hapi/marker'), {
        value: map
    });
}
```

**Comment by hueniverse** [comment]
Wasn't aware of `Symbol.for()`... any reason to not just use that and get rid of this module?
